In [104]:
#!/usr/bin/env python
# coding: utf-8

# import packages
# Note: You cannot import any other packages!
import numpy as np
import matplotlib.pyplot as plt
import csv
import math
import random
import seaborn as sns

In [105]:
# Global attributes
# Do not change anything here except TODO 1 
StudentID = '108062313' # TODO 1 : Fill your student ID here
input_dataroot = 'input.csv' # Please name your input csv file as 'input.csv'
output_dataroot = StudentID + '_basic_prediction.csv' # Output file will be named as '[StudentID]_basic_prediction.csv'

input_datalist =  [] # Initial datalist, saved as numpy array
output_datalist =  [] # Your prediction, should be 20 * 2 matrix and saved as numpy array
                      # The format of each row should be [Date, TSMC_Price_Prediction] 
                      # e.g. ['2021/10/15', 512]

# You can add your own global attributes here

In [106]:
# Read input csv to datalist
with open(input_dataroot, newline='') as csvfile:
    input_datalist = np.array(list(csv.reader(csvfile)))

In [107]:
def SplitData():
# TODO 2: Split data, 2021/10/15 ~ 2021/11/11 for testing data, and the other for training data and validation data 
    validation = input_datalist[0:30,:]
    training = input_datalist[0:158,:]
    test = input_datalist[159:186,:]
    return test, training, validation
#     val_df = val_df.reset_index()
test_datalist, training_datalist, validation_list= SplitData()
# print(training_datalist)



In [208]:
def PreprocessData(datalist):
# TODO 3: Preprocess your data  e.g. split datalist to x_datalist and y_datalist
    temp=[]
    temp2=[]
    X_train=[]
    X2_train=[]
    X3_train=[]
    Y_train=[]
    date=[]
    for i in range (len(datalist)):
        temp.append(1)
        X_train.append(float(datalist[i][1]))
        X2_train.append(float(datalist[i][1])**2)
        X3_train.append(float(datalist[i][1])**3)
        Y_train.append(float(datalist[i][2]))
    X_train=[X2_train,X_train,temp]
    X_train=np.array(X_train)
    X_train=X_train.T
    return X_train, Y_train
X_train, Y_train = PreprocessData(training_datalist)
X_test, Y_test = PreprocessData(test_datalist)
print(X_train)
# print(X_train)
# plt.figure()   

# plt.scatter(X_train[:,0], Y_train, color='red')
# plt.show() 

[[6.272640e+05 7.920000e+02 1.000000e+00]
 [6.352090e+05 7.970000e+02 1.000000e+00]
 [6.272640e+05 7.920000e+02 1.000000e+00]
 [6.384010e+05 7.990000e+02 1.000000e+00]
 [7.022440e+05 8.380000e+02 1.000000e+00]
 [7.242010e+05 8.510000e+02 1.000000e+00]
 [7.157160e+05 8.460000e+02 1.000000e+00]
 [7.814560e+05 8.840000e+02 1.000000e+00]
 [7.413210e+05 8.610000e+02 1.000000e+00]
 [7.225000e+05 8.500000e+02 1.000000e+00]
 [7.123360e+05 8.440000e+02 1.000000e+00]
 [7.726410e+05 8.790000e+02 1.000000e+00]
 [7.603840e+05 8.720000e+02 1.000000e+00]
 [8.723560e+05 9.340000e+02 1.000000e+00]
 [8.408890e+05 9.170000e+02 1.000000e+00]
 [8.281000e+05 9.100000e+02 1.000000e+00]
 [7.586410e+05 8.710000e+02 1.000000e+00]
 [8.046090e+05 8.970000e+02 1.000000e+00]
 [7.551610e+05 8.690000e+02 1.000000e+00]
 [7.656250e+05 8.750000e+02 1.000000e+00]
 [8.190250e+05 9.050000e+02 1.000000e+00]
 [8.667610e+05 9.310000e+02 1.000000e+00]
 [9.025000e+05 9.500000e+02 1.000000e+00]
 [8.949160e+05 9.460000e+02 1.0000

In [217]:
def CountLoss(y, y_):
# TODO 5: Count loss of training and validation data
    j=[0,0,0]
    s=0
    for i in range (len(y)):
        difference=y_[i]-y[i]
        s=s+abs(difference)
        j=j+(difference*X_train[i]) 
    j=j*2
#     print(s/len(y))
#     print("========")
    return j



In [218]:
A=np.array([1,2])
B=np.array([3,4])
print(A*B)

[3 8]


In [221]:
def Regression(X_train, Y_train, learning_rate=[1e-15,1e-9,1e-3], iteration=1000):
# TODO 4: Implement regression
    w=np.array([0,0,0])
    for i in range (iteration):
        y_=[]
        for j in range (len(X_train)):
            prediction=np.dot(w.T,X_train[j])
            y_.append(prediction)
        g=CountLoss(Y_train,y_)
        w=w-learning_rate*g   
#         print(w)
#         print(evaluate(X_test, Y_test, w))
#     print(y_)
    return w
w=Regression(X_train, Y_train)
print(evaluate(X_test, Y_test, w))

15.658247564270798
2.5873800089692414


In [220]:
print(evaluate(X_test, Y_test, w))

15.658247564270798
2.5873800089692414


In [216]:
def evaluate(x,y,w):
    prediction=0
    s=0
    for i in range(len(x)):
        y_=np.dot(w,x[i])
        s=s+abs(y[i]-y_)
        prediction=prediction+abs((y[i]-y_)/y[i])
#         print(y[i])
#         print(y[i]-y_)
#         print((y[i]-y_)/y[i])
#         print("=======")
    prediction=prediction/len(x)
    print(s/len(x))
    return prediction*100


In [113]:
def MakePrediction(x,y,w,date):
# TODO 6: Make prediction of testing data 
    prediction=[]
    day=[]
    for i in range(len(x)):
        y_=np.dot(w,x[i])
        prediction.append(int(y_))
    prediction=[date,prediction]
    return prediction




In [114]:
# TODO 7: Call functions of TODO 2 to TODO 6, train the model and make prediction
test_datalist, training_datalist, validation_list = SplitData()
X_train, Y_train, X_test, Y_test, date = PreprocessData(training_datalist, test_datalist)
w=Regression(X_train, Y_train)
output_datalist=np.array(MakePrediction(X_test, Y_test, w, date)).T
# # Write prediction to output csv
# print(output_datalist)
# with open(output_dataroot, 'w', newline='', encoding="utf-8") as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerow(['Date', 'TSMC Price'])
#     for row in output_datalist:
#         writer.writerow(row)

596.2088607594936
491.89344573568343
405.8853231183346
334.9715741342871
276.50314531682506
228.29589048455574
188.54897979329905
155.77762795014877
128.7576285853822
106.74109026732204
88.82528315256602
74.3848366680248
62.797962370703296
53.73033831425515
46.583657182234994
40.72642913528918
36.64976723187791
33.721730534511956
31.75318076176549
30.43996858395701
[0.62229641 0.00067036]
[['2021/8/31' '560']
 ['2021/9/1' '576']
 ['2021/9/2' '580']
 ['2021/9/3' '571']
 ['2021/9/6' '557']
 ['2021/9/7' '561']
 ['2021/9/8' '567']
 ['2021/9/9' '560']
 ['2021/9/10' '575']
 ['2021/9/13' '576']
 ['2021/9/14' '589']
 ['2021/9/15' '581']
 ['2021/9/16' '582']
 ['2021/9/17' '584']
 ['2021/9/22' '566']
 ['2021/9/23' '569']
 ['2021/9/24' '572']
 ['2021/9/27' '596']
 ['2021/9/28' '595']
 ['2021/9/29' '568']
 ['2021/9/30' '563']
 ['2021/10/1' '550']
 ['2021/10/4' '555']
 ['2021/10/5' '539']
 ['2021/10/6' '542']
 ['2021/10/7' '566']
 ['2021/10/8' '566']]
