In [1]:
#!/usr/bin/env python
# coding: utf-8

# import packages
# Note: You cannot import any other packages!
import numpy as np
import matplotlib.pyplot as plt
import csv
import math
import random

In [152]:
# Global attributes
# Do not change anything here except TODO 1 
StudentID = '108062313' # TODO 1 : Fill your student ID here
input_dataroot = 'large_sample_input.csv' # Please name your input csv file as 'input.csv'
output_dataroot = StudentID + '_basic_prediction.csv' # Output file will be named as '[StudentID]_basic_prediction.csv'

input_datalist =  [] # Initial datalist, saved as numpy array
output_datalist =  [] # Your prediction, should be 20 * 2 matrix and saved as numpy array
                      # The format of each row should be [Date, TSMC_Price_Prediction] 
                      # e.g. ['2021/10/15', 512]

# You can add your own global attributes here
test_datalist=[]
training_datalist=[]
validation_list=[]

In [153]:
# Read input csv to datalist
with open(input_dataroot, newline='') as csvfile:
    input_datalist = np.array(list(csv.reader(csvfile)))

In [197]:
def SplitData():
# TODO 2: Split data, 2021/10/15 ~ 2021/11/11 for testing data, and the other for training data and validation data 
#     test = input_datalist[1:60,:]
#     training = input_datalist[61:381,:]
#     validation = input_datalist[382:426,:]
    test = input_datalist[247:277,:]
    training = input_datalist[278:381,:]
    validation = input_datalist[392:426,:]


    return test, training, validation
#     val_df = val_df.reset_index()
test_datalist, training_datalist, validation_list = SplitData()
# print(test_datalist)

In [199]:
def PreprocessData(training_datalist, test_datalist):
# TODO 3: Preprocess your data  e.g. split datalist to x_datalist and y_datalist
    temp=[]
    temp2=[]
    X_train=[]
    X2_train=[]
    X3_train=[]
    Y_train=[]
    X_test=[]
    X2_test=[]
    X3_test=[]
    Y_test=[]
    for i in range (len(training_datalist)):
        temp.append(1)
        X_train.append(float(training_datalist[i][1]))
        X2_train.append(float(training_datalist[i][1])*float(training_datalist[i][1])*0.01)
        X3_train.append(float(training_datalist[i][1])*float(training_datalist[i][1])*float(training_datalist[i][1])*0.0001)
        Y_train.append(float(training_datalist[i][2]))
    for j in range (len(test_datalist)):
        temp2.append(1)
        X_test.append(float(test_datalist[j][1]))
        X2_test.append(float(test_datalist[j][1])*float(test_datalist[j][1])*0.01)
        X3_test.append(float(training_datalist[j][1])*float(training_datalist[j][1])*float(training_datalist[j][1])*0.0001)
        Y_test.append(float(test_datalist[j][2]))
        
    X_train=[X3_train,X2_train,X_train,temp]
    X_train=np.array(X_train)
    X_train=X_train.T
    
    X_test=[X3_test,X2_test,X_test,temp2]
    X_test=np.array(X_test)
    X_test=X_test.T
    
    return X_train, Y_train, X_test, Y_test
X_train, Y_train, X_test, Y_test = PreprocessData(training_datalist, test_datalist)
print(X_train)

[[7.19323136e+04 8.02816000e+03 8.96000000e+02 1.00000000e+00]
 [7.29000000e+04 8.10000000e+03 9.00000000e+02 1.00000000e+00]
 [8.04357000e+04 8.64900000e+03 9.30000000e+02 1.00000000e+00]
 [7.21734273e+04 8.04609000e+03 8.97000000e+02 1.00000000e+00]
 [6.88465387e+04 7.79689000e+03 8.83000000e+02 1.00000000e+00]
 [6.51714363e+04 7.51689000e+03 8.67000000e+02 1.00000000e+00]
 [6.79151439e+04 7.72641000e+03 8.79000000e+02 1.00000000e+00]
 [6.44972544e+04 7.46496000e+03 8.64000000e+02 1.00000000e+00]
 [7.00227072e+04 7.88544000e+03 8.88000000e+02 1.00000000e+00]
 [7.26572699e+04 8.08201000e+03 8.99000000e+02 1.00000000e+00]
 [7.46142643e+04 8.22649000e+03 9.07000000e+02 1.00000000e+00]
 [7.76151559e+04 8.44561000e+03 9.19000000e+02 1.00000000e+00]
 [7.48613312e+04 8.24464000e+03 9.08000000e+02 1.00000000e+00]
 [7.36314327e+04 8.15409000e+03 9.03000000e+02 1.00000000e+00]
 [6.93154125e+04 7.83225000e+03 8.85000000e+02 1.00000000e+00]
 [6.83797841e+04 7.76161000e+03 8.81000000e+02 1.000000

In [202]:
def CountLoss(y, y_):
# TODO 5: Count loss of training and validation data
    j=[0,0,0,0]
    s=0
    for i in range (len(y)):
        difference=y_[i]-y[i]
        s=s+abs(difference)
        j=j+(difference*X_train[i]) 
    j=j*2
    print(s/len(y))
    print("========")
    return j


In [209]:
def Regression(X_train, Y_train, learning_rate=1e-10, iteration=20):
# TODO 4: Implement regression
    w=np.array([0,0,0,0])
    for i in range (iteration):
        y_=[]
        for j in range (len(X_train)):
            prediction=np.dot(w.T,X_train[j])
            y_.append(prediction)
        g=CountLoss(Y_train,y_)
        w=w-learning_rate*g/len(X_train)    
    print(w)
#     print(y_)
    return w
w=Regression(X_train, Y_train)
print(evaluate(X_train, Y_train, w))

593.4077669902913
324.34561973498063
224.11510104724098
115.8924112943824
111.92205350698845
76.03739644856826
82.44043838119086
71.62330150684994
75.86037331462992
72.73496077342986
74.38290223621762
73.3423626285539
73.92214470387464
73.55117574696699
73.75228323614763
73.61869651128555
73.68756676357933
73.63736009589061
73.65923873492687
73.63819939435214
[6.48529455e-03 9.06311288e-04 1.17124509e-04 1.44678737e-07]
0.12382556804051474


In [208]:
print(evaluate(X_test, Y_test, w))

0.15669365340766453


In [116]:
def evaluate(x,y,w):
    prediction=0
    for i in range(len(x)):
        y_=np.dot(w,x[i])
        prediction=prediction+abs((y[i]-y_)/y[i])
#         print(y[i])
#         print(y[i]-y_)
#         print((y[i]-y_)/y[i])
#         print("=======")
    prediction=prediction/len(x)
    return prediction


In [ ]:
def MakePrediction():
# TODO 6: Make prediction of testing data 




In [ ]:
# TODO 7: Call functions of TODO 2 to TODO 6, train the model and make prediction
test_datalist, training_datalist, validation_list = SplitData()
X_train, Y_train, X_test, Y_test = PreprocessData(training_datalist, test_datalist)
w=Regression(X_train, Y_train)

# Write prediction to output csv
with open(output_dataroot, 'w', newline='', encoding="utf-8") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Date', 'TSMC Price'])
    
    for row in output_datalist:
        writer.writerow(row)